application:
  max-allowed-books: 3
server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    url: jdbc:h2:file:./data/library
  h2:
    # http://localhost:port/h2-console
    console:
      enabled: true
  # всегда запускать data.sql при старте с embedded СУБД:
  sql:
    init:
      platform: h2
      mode: always

logging:
  pattern:
    console: "%clr(%d{HH:mm}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(%25.25logger{0}){cyan} %clr(:){faint} %m%n%wEx"
